### ISSUE TITLE
cannot initialize device

### ISSUE THREAD

**Issue by homonto** [solinnovay/Python_ST7789#3]
hi there,
I just connected this display and I am trying to use your library
unfortunately there is an issue
my display is 7 pin from Aliexpres 
I connected as following:
VCC, GND 
SCL= GPIO 11, PIN 23
SDA=GPIO 10, PIN 19
RESET=GPIO 27, PIN 13
DC=GPIO 25, PIN 22
LED(BACKLIGHT)=GPIO 24, PIN 18

same as in your example: clock_EN.py:
RST = 27
DC  = 25
LED = 24

when running the example script always the same error:

`$  python3 clock_EN.py 
Traceback (most recent call last):
  File "clock_EN.py", line 36, in <module>
    disp = TFT.ST7789(spi=SPI.SpiDev(SPI_PORT, SPI_DEVICE, max_speed_hz=SPI_SPEED_HZ),
  File "/usr/local/lib/python3.7/dist-packages/Adafruit_GPIO-1.0.4-py3.7.egg/Adafruit_GPIO/SPI.py", line 46, in __init__
SystemError: error return without exception set
`

I am not sure how to make it working
the power is there (I can see some backlight on) but nothing else
any help would be appreciated

thx

**Comment by whabilly** [comment]
Hello, same issue here. Have you found a fix??? Thank you.
